Merge Ado's navigation to master
GalileoSchool/GalileoSchool.github.io pull request #3
Opened 2019-09-30 17:07 UTC by ViliamVadocz

2019-10-01 17:01 UTC, AdrianJakubcik commented
Btw There is no more need for the include.js in js folder and the navigation.html is not used anymore.

2019-10-10 17:41 UTC, DiscreteConcrete requested changes
Very nice!! I added comments mostly regarding formatting and code hygiene.
A general style comment would be that in many companies, there is a preference for a maximum line length of 80 characters - that way the reviews are much nicer and you can view the code in a narrower editor.
We could try to use a "linter" like "ES-Lint" or a tool like "Prettier" for this, but maybe later :) 
I will do a second review - a review of functionality later, but it's looking good.

2019-10-10 17:41 UTC, DiscreteConcrete commented on js/navigation.js
> +*/
these expanded comments are nicer when you add an extra space before, so that the asterisks are aligned

2019-10-10 17:41 UTC, DiscreteConcrete commented on css/nav_style.css
> +/* This is the default style that will be used, in-case there are no media queries this is the default style*/
in case is two separate words

2019-10-10 17:41 UTC, DiscreteConcrete commented on css/nav_style.css
> +/* This is the default style that will be used, in-case there are no media queries this is the default style*/
let's be a bit cleaner on formatting here: let's put space before the `*/` in comments

2019-10-10 17:41 UTC, DiscreteConcrete commented on css/nav_style.css
> +.nav-desk{
let's be a bit stricter on formatting here as well: space before `{`

2019-10-10 17:41 UTC, DiscreteConcrete commented on css/nav_style.css
> +    background-color:#e9e9e9;
indent

2019-10-10 17:41 UTC, DiscreteConcrete commented on css/nav_style.css
> +    background-color: #e7e7e7;
indent

2019-10-10 17:41 UTC, DiscreteConcrete commented on css/nav_style.css
> +.nav-desk{
what does the "desk" mean here? Desktop? the naming is a bit confusing

2019-10-10 17:41 UTC, DiscreteConcrete commented on css/nav_style.css
> +.nav-desk > ul{
I really like how verbose you are in some parts of the codebase - but here there are some non-obvious properties that we are evoking (like `padding-inline-start`) - can we add some more comments?

2019-10-10 17:41 UTC, DiscreteConcrete commented on css/nav_style.css
> +    z-index: 4;
why 4?

2019-10-10 17:41 UTC, DiscreteConcrete commented on css/nav_style.css
> +/* This is a query that tells the browser what style to use in case its width is > or = to 740px */
it says 670 in the code - so why 740?

2019-10-10 17:41 UTC, DiscreteConcrete commented on index.html
> +<head>
yeh, this is a popular indentation choice - maybe let's add a quick comment that this is deliberate - so those who read this code don't think that we're just lazy with indentation!

2019-10-10 17:41 UTC, DiscreteConcrete commented on js/navigation.js
> +var NavMenu = document.getElementById('Navigation');
why is one const and the other one var?

2019-10-10 17:41 UTC, DiscreteConcrete commented on js/navigation.js
> +    {
we're a bit inconsistent here about where the `{` goes - maybe would be nicer on previous line

2019-10-10 17:41 UTC, DiscreteConcrete commented on js/navigation.js
> +            document.querySelector('.content').classList.remove('blur');
we're a bit inconsistent here about usage of `{` and `}` - the general rule of thumb in the industry is that if the `if` or `else` and the effect are on the same single line, we don't use braces. however, when it's on the next line(s), then we always use braces.

2019-10-10 17:41 UTC, DiscreteConcrete commented on js/navigation.js
> +        if(document.querySelector('.content').classList.contains('blur'))
we're also inconsistent about space after `if` - in the industry it is more popular to consistently place a space after the `if`

2019-10-10 18:00 UTC, AdrianJakubcik commented on css/nav_style.css
> +/* This is the default style that will be used, in-case there are no media queries this is the default style*/
Yeah I wasn't sure 'bout that one so I went with the double case. 🤣

2019-10-10 19:39 UTC, AdrianJakubcik commented on js/navigation.js
> +var NavMenu = document.getElementById('Navigation');
My mistake sorry, fixed it.

2019-10-10 19:45 UTC, AdrianJakubcik commented on css/nav_style.css
> +/* This is a query that tells the browser what style to use in case its width is > or = to 740px */
Originally it was 740 but after a little bit of debuging I chose 670 will be better, and forgot to change the comment. Thank you for pointing out :) 👍

2019-10-10 22:04 UTC, AdrianJakubcik commented on css/nav_style.css
> +    z-index: 4;
Ohh that was just for a debug purpose, forgot to remove it. Sorry 🤕

2019-11-10 14:58 UTC, DiscreteConcrete requested changes

2019-11-10 14:58 UTC, DiscreteConcrete commented on css/nav_style.css
> +    /* I will be using vw (view-width) units, this is the measure of the browsers content window width */
let's put comments ABOVE the lines on which they comment

2019-11-10 14:58 UTC, DiscreteConcrete commented on css/nav_style.css
> +.nav-desk>ul {
a more common industry standard is to have spaces around the `>`

2019-11-10 14:58 UTC, DiscreteConcrete commented on css/nav_style.css
> +div.nav-phone.lang{
let's adopt the convention of space before `{`

2019-11-10 14:58 UTC, DiscreteConcrete commented on css/nav_style.css
> +.nav-phone.language-dropdown-content {
this is inconsistent - maybe let's adopt the convention of spaces between classes (before `.`) in CSS blocks?

2019-11-10 14:58 UTC, DiscreteConcrete commented on css/nav_style.css
> +    /*border-radius: 0.25vw;*/
do we need to keep this as a comment?

2019-11-10 14:58 UTC, DiscreteConcrete commented on css/nav_style.css
> +    /* !important is a special css attribute that overrides any styles that could possibly clash with it (It's like the Principle of Gymnasium compared to the Teacher of Gymnasium */
missing ending `)` in comment
also, in English Gymnasium means a workout/sports gym. High school is a better translation :)

2019-11-10 14:58 UTC, DiscreteConcrete commented on css/nav_style.css
> +    /*margin-left: 2vw !important;*/
do we need to keep this?

2019-11-10 14:58 UTC, DiscreteConcrete commented on css/nav_style.css
> +
why so many empty lines between them?

2019-11-10 14:58 UTC, DiscreteConcrete commented on css/nav_style.css
> +/* This is a query that tells the browser what style to use in case its width is > or = to 670px (px stands for pixels) */
let's explain how we got to 670 - because the next person working on it might wonder why such exact number

2019-11-10 14:58 UTC, DiscreteConcrete commented on css/nav_style.css
> +        /*border-bottom: 2px solid black;*/
do we need to keep this?

2019-11-10 14:58 UTC, DiscreteConcrete commented on index.html
> +<!--This Indention is Totally Legal and We Are 100% Certain About This-->
why so many capitalised letters? :)

2019-11-10 14:58 UTC, DiscreteConcrete commented on index.html
> +<!--This Indention is Totally Legal and We Are 100% Certain About This-->
Also, there tends to be a pedantic convention in the community that there should be a space after `<!--` and before `-->` - and also in CSS after `/*` and before `*/`

2019-11-10 14:58 UTC, DiscreteConcrete commented on index.html
> +    <!-- ADD COMMENT -->
?

2019-11-10 14:58 UTC, DiscreteConcrete commented on index.html
> +                        <div id="search" class="nav-phone search"><img id="menu-img" src="images/icons/search.png">
maybe would be nicer if img was on the next line?

2019-11-10 14:58 UTC, DiscreteConcrete commented on index.html
> +                        <li class="nav-phone logo"><img id="logo" src="images/logo.jpg"></li>
maybe would be nicer if img had its own line?

2019-11-10 14:58 UTC, DiscreteConcrete commented on js/jquery.js
> +// This tells the browser to execute certain function as soon as it is ready (as soon as the page is fully loaded)
`to execute certain function` sounds grammatically awkward - maybe an article would help or maybe it should be plural?

2019-11-10 14:58 UTC, DiscreteConcrete commented on js/jquery.js
> +    // Using Id I'm selecting the element with the given Id in this case it is the navigation button
i feel some punctuation here would help

2019-11-10 14:58 UTC, DiscreteConcrete commented on js/jquery.js
> +        $('.navbar').slideToggle('fast');
there seems to be a lot happening in this function - it's a bit hard to follow!

2019-11-10 14:58 UTC, DiscreteConcrete commented on js/jquery.js
> +        });
would look nicer if the `);` was on the next line

2019-11-10 14:58 UTC, DiscreteConcrete commented on js/jquery.js
> +    $(document).click(function() {
this feels a bit dense

2019-11-10 14:58 UTC, DiscreteConcrete commented on js/jquery.js
> +        if (!$('.language-dropdown-content').is(":hover") && !$('.language-dropdown-content').is(":hidden") && !$(langBtn).is(":hover")) {
we are a little bit inconsistent in using `'` and `"`

2019-11-10 14:58 UTC, DiscreteConcrete commented on js/jquery.js
> +    //Use the code below for the desktop version (It is the hover version)
if we need the code below, maybe we can explain why we commented it out for now?

2019-11-10 14:58 UTC, DiscreteConcrete commented on js/navigation.js
> +/**
maybe we're missing an actual explanation of what this does?

2019-11-10 14:58 UTC, DiscreteConcrete commented on js/navigation.js
> +if (parsed_dir == "sk")
usually, when the if is multiline, the convention is usually to include the `{` and `}`

2019-11-10 14:58 UTC, DiscreteConcrete commented on js/navigation.js
> +const menuBtn = document.getElementById("nav-btn");
use of const is interesting: usually people would either use `var` everywhere (old javascript) or `const` and `let` instead (but not `var`). What is our reason to use `const` and `var`? and how much of the world supports the new javascript with `const` and `let` by now?

2019-11-10 14:58 UTC, DiscreteConcrete commented on js/navigation.js
> + * Difficulty: Easy
do we still need the difficulty indicators?

2019-11-10 14:58 UTC, DiscreteConcrete commented on js/navigation.js
> + * @description What this function does to achieve the effect of hiding and showing our menu after clicking a button on a mobile device,
I feel this description feels a bit grammatically awkward

2019-11-10 14:58 UTC, DiscreteConcrete commented on js/navigation.js
> + * @description What this function does to achieve the effect of hiding and showing our menu after clicking a button on a mobile device,
also, for what reasons do we use the @description here, but not in many other places?

2019-11-10 14:58 UTC, DiscreteConcrete commented on js/navigation.js
> +        if (window.getComputedStyle(NavMenu).display == "none" || window.getComputedStyle(NavMenu).display == "block") {
I like this entire function - but maybe we could add a tiny bit more explanation?

2019-11-10 14:58 UTC, DiscreteConcrete commented on js/navigation.js
> +function resetMenu() {
maybe we can explain what this does?

2019-11-10 21:37 UTC, AdrianJakubcik commented on js/navigation.js
> +const menuBtn = document.getElementById("nav-btn");
I decided to use `const` for things that are constantly the same no matter what. Like html elements, when I select any html element I know it won't be changing anytime soon, thus I assign it as a `const`. But things that may change throughout the code are assigned as `var` meaning variable. Variable is something that may change because it is vary-able or able to vary. It's totally just my way of dividing constants and non-constants. Btw the support for `const` is around `98.97%`.

2019-11-10 21:39 UTC, AdrianJakubcik commented on js/navigation.js
> + * Difficulty: Easy
I'm leaving them there for the others, if they would like to start with javascript I'm trying to show them what things are easier to do and which are harder to do.

2019-11-10 21:51 UTC, AdrianJakubcik commented on js/navigation.js
> + * @description What this function does to achieve the effect of hiding and showing our menu after clicking a button on a mobile device,
As I was playing a little bit with Js it seems that Javascript only allows to add description to function, class or any other object that can be called during script execution more than once. Meaning I can't add description to code that is not enclosed and turned into a 'static' object, it's not static but I can't find the right word for it atm. This is the reason why not many things have `@description` but most of my function documentations do include a `@description`.

2019-11-10 22:29 UTC, AdrianJakubcik commented on js/jquery.js
> +        });
My formatter always moves it back after the `}`. I'm sorry for that.

2019-11-11 20:37 UTC, ViliamVadocz commented on js/navigation.js
> + * Difficulty: Easy
I think they just make the code messier.

2019-11-11 20:40 UTC, ViliamVadocz commented on css/nav_style.css
> +.nav-phone.language-dropdown-content {
I think that has a different meaning based on this thread: https://stackoverflow.com/questions/5116288/how-to-select-an-element-with-2-classes

2019-11-11 20:53 UTC, AdrianJakubcik commented on js/navigation.js
> + * Difficulty: Easy
As long as I know the point of a documentation is to include any helpful information that would explain the purpose of a function and/or they way it works. By helpful information I mean anything that can help others understand the function.

2019-11-11 21:24 UTC, DiscreteConcrete commented on css/nav_style.css
> +.nav-phone.language-dropdown-content {
completely missed that!

2019-11-11 21:26 UTC, DiscreteConcrete commented on js/navigation.js
> +const menuBtn = document.getElementById("nav-btn");
Good! Now what reasons do we have to use `var` over `let`?

2019-11-11 21:28 UTC, DiscreteConcrete commented on js/navigation.js
> + * Difficulty: Easy
I agree with the general point of helping others, but I am sure there is a level where we would be over-commenting (for example if I was to talk about what I had for lunch while coding those parts of code). In this particular case, I feel like we are slightly overstepping the line and it is a bit unnecessary - in other words I don't think there is that much value and giving so many lines of code to something with so little value feels like overcommenting

2019-11-11 21:29 UTC, DiscreteConcrete commented on js/navigation.js
> + * @description What this function does to achieve the effect of hiding and showing our menu after clicking a button on a mobile device,
fair!

2019-11-11 21:40 UTC, DiscreteConcrete requested changes

2019-11-11 21:40 UTC, DiscreteConcrete commented on css/nav_style.css
> +    /* !important is a special css attribute that overrides any styles that could possibly clash with it (It's like the Principle of High School compared to the Teacher of High School) */
move comment above what interests us

2019-11-11 21:40 UTC, DiscreteConcrete commented on css/nav_style.css
> +
this is still unresolved...

2019-11-11 21:40 UTC, DiscreteConcrete commented on js/jquery.js
> +        });
not convinced

2019-11-11 21:40 UTC, DiscreteConcrete commented on js/navigation.js
> +function resetMenu() {
I think I am still a bit confused about this function - I understand what it does, but if I change something in the navbar, how will I know I have to edit something here as well? This has a high likelihood of breaking in the future! What can we do about that?

2019-11-12 14:18 UTC, ViliamVadocz commented on css/nav_style.css
> +    /* !important is a special css attribute that overrides any styles that could possibly clash with it (It's like the Principle of Gymnasium compared to the Teacher of Gymnasium */
also note principle  != principal

2019-11-12 14:25 UTC, ViliamVadocz commented
Would be nice if we resolved already solved comments so it is easier to see what needs addressing.

2019-11-13 22:14 UTC, ViliamVadocz commented on js/navigation.js
> +function resetMenu() {
Maybe we could reuse the function found in `jquery.js` which activates on click to toggle the menu visibility which would reduce the amount of code that needs to be updated if anything changes.

2019-11-13 23:59 UTC, DiscreteConcrete approved these changes

2019-11-14 00:01 UTC, merged